// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAutoPlan = "auto_plan"

// AutoPlan mapped from table <auto_plan>
type AutoPlan struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	PlanID       string         `gorm:"column:plan_id;not null" json:"plan_id"`                                 // 计划ID
	RankID       int64          `gorm:"column:rank_id;not null" json:"rank_id"`                                 // 序号ID
	TeamID       string         `gorm:"column:team_id;not null" json:"team_id"`                                 // 团队ID
	PlanName     string         `gorm:"column:plan_name;not null" json:"plan_name"`                             // 计划名称
	TaskType     int32          `gorm:"column:task_type;not null;default:1" json:"task_type"`                   // 计划类型：1-普通任务，2-定时任务
	Status       int32          `gorm:"column:status;not null;default:1" json:"status"`                         // 计划状：1-未开始，2-进行中
	CreateUserID string         `gorm:"column:create_user_id;not null" json:"create_user_id"`                   // 创建人id
	RunUserID    string         `gorm:"column:run_user_id;not null" json:"run_user_id"`                         // 运行人id
	Remark       string         `gorm:"column:remark" json:"remark"`                                            // 备注
	RunCount     int64          `gorm:"column:run_count;not null" json:"run_count"`                             // 运行次数
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName AutoPlan's table name
func (*AutoPlan) TableName() string {
	return TableNameAutoPlan
}
