// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAutoPlanReport = "auto_plan_report"

// AutoPlanReport mapped from table <auto_plan_report>
type AutoPlanReport struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ReportID         string         `gorm:"column:report_id;not null" json:"report_id"`                               // 报告ID
	PlanID           string         `gorm:"column:plan_id;not null" json:"plan_id"`                                   // 计划ID
	RankID           int64          `gorm:"column:rank_id;not null" json:"rank_id"`                                   // 序号ID
	PlanName         string         `gorm:"column:plan_name;not null" json:"plan_name"`                               // 计划名称
	TeamID           string         `gorm:"column:team_id;not null" json:"team_id"`                                   // 团队ID
	TaskType         int32          `gorm:"column:task_type;not null" json:"task_type"`                               // 任务类型
	TaskMode         int32          `gorm:"column:task_mode;not null" json:"task_mode"`                               // 运行模式：1-按测试用例运行
	ControlMode      int32          `gorm:"column:control_mode;not null" json:"control_mode"`                         // 控制模式：0-集中模式，1-单独模式
	SceneRunOrder    int32          `gorm:"column:scene_run_order;not null;default:1" json:"scene_run_order"`         // 场景运行次序：1-顺序执行，2-同时执行
	TestCaseRunOrder int32          `gorm:"column:test_case_run_order;not null;default:1" json:"test_case_run_order"` // 测试用例运行次序：1-顺序执行，2-同时执行
	RunDurationTime  int64          `gorm:"column:run_duration_time;not null" json:"run_duration_time"`               // 任务运行持续时长
	Status           int32          `gorm:"column:status;not null;default:1" json:"status"`                           // 报告状态1:进行中，2:已完成
	RunUserID        string         `gorm:"column:run_user_id;not null;default:0" json:"run_user_id"`                 // 启动人id
	Remark           string         `gorm:"column:remark;not null" json:"remark"`                                     // 备注
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`   // 创建时间（执行时间）
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`   // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                      // 删除时间
}

// TableName AutoPlanReport's table name
func (*AutoPlanReport) TableName() string {
	return TableNameAutoPlanReport
}
