// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameElement = "element"

// Element mapped from table <element>
type Element struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // id
	ElementID     string         `gorm:"column:element_id;not null" json:"element_id"`                           // 全局唯一ID
	ElementType   string         `gorm:"column:element_type;not null" json:"element_type"`                       // 类型：文件夹，元素
	TeamID        string         `gorm:"column:team_id;not null" json:"team_id"`                                 // 团队id
	Name          string         `gorm:"column:name;not null" json:"name"`                                       // 名称
	ParentID      string         `gorm:"column:parent_id;not null;default:0" json:"parent_id"`                   // 父级ID
	Locators      string         `gorm:"column:locators" json:"locators"`                                        // 定位元素属性
	Sort          int32          `gorm:"column:sort;not null" json:"sort"`                                       // 排序
	Version       int32          `gorm:"column:version;not null" json:"version"`                                 // 产品版本号
	CreatedUserID string         `gorm:"column:created_user_id;not null" json:"created_user_id"`                 // 创建人ID
	Description   string         `gorm:"column:description;not null" json:"description"`                         // 备注
	Source        int32          `gorm:"column:source;not null" json:"source"`                                   // 数据来源：0-元素管理，1-场景管理
	SourceID      string         `gorm:"column:source_id;not null" json:"source_id"`                             // 引用来源ID
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName Element's table name
func (*Element) TableName() string {
	return TableNameElement
}
