// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMachine = "machine"

// Machine mapped from table <machine>
type Machine struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	Region            string         `gorm:"column:region;not null" json:"region"`                                   // 所属区域
	IP                string         `gorm:"column:ip;not null" json:"ip"`                                           // 机器IP
	Port              int32          `gorm:"column:port;not null" json:"port"`                                       // 端口
	Name              string         `gorm:"column:name;not null" json:"name"`                                       // 机器名称
	CPUUsage          float32        `gorm:"column:cpu_usage;not null" json:"cpu_usage"`                             // CPU使用率
	CPULoadOne        float32        `gorm:"column:cpu_load_one;not null" json:"cpu_load_one"`                       // CPU-1分钟内平均负载
	CPULoadFive       float32        `gorm:"column:cpu_load_five;not null" json:"cpu_load_five"`                     // CPU-5分钟内平均负载
	CPULoadFifteen    float32        `gorm:"column:cpu_load_fifteen;not null" json:"cpu_load_fifteen"`               // CPU-15分钟内平均负载
	MemUsage          float32        `gorm:"column:mem_usage;not null" json:"mem_usage"`                             // 内存使用率
	DiskUsage         float32        `gorm:"column:disk_usage;not null" json:"disk_usage"`                           // 磁盘使用率
	MaxGoroutines     int64          `gorm:"column:max_goroutines;not null" json:"max_goroutines"`                   // 最大协程数
	CurrentGoroutines int64          `gorm:"column:current_goroutines;not null" json:"current_goroutines"`           // 已用协程数
	ServerType        int32          `gorm:"column:server_type;not null;default:1" json:"server_type"`               // 机器类型：1-主力机器，2-备用机器
	Status            int32          `gorm:"column:status;not null;default:1" json:"status"`                         // 机器状态：1-使用中，2-已卸载
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 修改时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName Machine's table name
func (*Machine) TableName() string {
	return TableNameMachine
}
