// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOperation = "operation"

// Operation mapped from table <operation>
type Operation struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	TeamID    string         `gorm:"column:team_id;not null" json:"team_id"`            // 团队ID
	UserID    string         `gorm:"column:user_id;not null" json:"user_id"`            // 用户ID
	Category  int32          `gorm:"column:category;not null" json:"category"`          // 日志类型：1-新建，2-修改，3-删除，4-运行，5-调试，6-执行
	Operate   int32          `gorm:"column:operate" json:"operate"`                     // {"操作类型":{1:创建文件夹,2:创建接口,3:创建分组,4:创建计划,5:创建场景,6:修改文件夹,7:修改接口,8:修改分组,9:修改计划,10:修改场景,11:克隆计划,12:删除报告,13:删除场景,14:删除计划,15:运行场景,16:运行计划,17:新建预设配置,18:修改并保存预设配置,19:删除预设配置}}
	Name      string         `gorm:"column:name;not null" json:"name"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Operation's table name
func (*Operation) TableName() string {
	return TableNameOperation
}
