// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID                 int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	OrderID            string         `gorm:"column:order_id;not null" json:"order_id"`                               // 订单号id
	PayTradeNo         string         `gorm:"column:pay_trade_no;not null" json:"pay_trade_no"`                       // 支付中心订单号
	TradeNo            string         `gorm:"column:trade_no;not null" json:"trade_no"`                               // 第三方订单号
	TeamID             string         `gorm:"column:team_id;not null" json:"team_id"`                                 // 团队id
	GoogsName          string         `gorm:"column:googs_name;not null" json:"googs_name"`                           // 商品名称
	OrderType          int32          `gorm:"column:order_type;not null" json:"order_type"`                           // 订单类型：1-新建团队，2-VUM资源包，3-升级团队，4-增加席位，5-套餐续期
	VumBuyVersionType  int32          `gorm:"column:vum_buy_version_type;not null" json:"vum_buy_version_type"`       // VUM套餐类型：1-A,2-B,3-C,4-D
	TeamBuyVersionType int32          `gorm:"column:team_buy_version_type;not null" json:"team_buy_version_type"`     // 团队套餐类型：1-个人版，2-团队版，3-企业版
	MaxConcurrence     int32          `gorm:"column:max_concurrence;not null" json:"max_concurrence"`                 // 最大并发数
	BuyNumber          int64          `gorm:"column:buy_number;not null" json:"buy_number"`                           // 购买数量（席位数量/VUM资源包数量）
	OrderAmount        float64        `gorm:"column:order_amount;not null" json:"order_amount"`                       // 订单金额
	Discounts          float64        `gorm:"column:discounts;not null" json:"discounts"`                             // 优惠金额
	RealAmount         float64        `gorm:"column:real_amount;not null" json:"real_amount"`                         // 实际付款金额
	PayType            int32          `gorm:"column:pay_type;not null;default:1" json:"pay_type"`                     // 支付方式：0-未知，1-微信，2-支付宝，3-银联，4-PayPal
	PayStatus          int32          `gorm:"column:pay_status;not null" json:"pay_status"`                           // 支付状态：0-待支付，1-支付成功，2-支付失败，3-支付中，4-已过期，5-已关闭
	GoodsValidDate     int32          `gorm:"column:goods_valid_date;not null" json:"goods_valid_date"`               // 商品的有效期（单位：月）
	FinishPayTime      time.Time      `gorm:"column:finish_pay_time" json:"finish_pay_time"`                          // 到账时间
	OpenInvoiceState   int32          `gorm:"column:open_invoice_state;not null" json:"open_invoice_state"`           // 发票申请状态：0-待开票，1-已开票，2-已作废
	PayUserID          string         `gorm:"column:pay_user_id;not null;default:0" json:"pay_user_id"`               // 支付人id
	CreatedAt          time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt          time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
