// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermissionOperationLog = "permission_operation_log"

// PermissionOperationLog mapped from table <permission_operation_log>
type PermissionOperationLog struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	Type      int32          `gorm:"column:type;not null" json:"type"`                  // 11:新建私有/公开团队  12:编辑团队名称  13编辑团队名称 21:创建成员  22:禁用账号   23:删除账号   24:更改成员的企业角色  25:邀请企业成员进团队  26:移除团队内成员  27:团队内成员权限设置   31:添加角色、保存更改   32:删除角色
	UserID    string         `gorm:"column:user_id;not null" json:"user_id"`            // 操作人id
	OldValue  string         `gorm:"column:old_value;not null" json:"old_value"`        // 旧值
	NewValue  string         `gorm:"column:new_value;not null" json:"new_value"`        // 新值
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName PermissionOperationLog's table name
func (*PermissionOperationLog) TableName() string {
	return TableNamePermissionOperationLog
}
