// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePublicFunction = "public_function"

// PublicFunction mapped from table <public_function>
type PublicFunction struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	Function     string         `gorm:"column:function;not null" json:"function"`                               // 函数
	FunctionName string         `gorm:"column:function_name;not null" json:"function_name"`                     // 函数名称
	Remark       string         `gorm:"column:remark;not null" json:"remark"`                                   // 备注
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 修改时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName PublicFunction's table name
func (*PublicFunction) TableName() string {
	return TableNamePublicFunction
}
