// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRolePermission = "role_permission"

// RolePermission mapped from table <role_permission>
type RolePermission struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`  // 主键id
	RoleID       string         `gorm:"column:role_id;not null" json:"role_id"`             // 角色id
	PermissionID int64          `gorm:"column:permission_id;not null" json:"permission_id"` // 权限id
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
