// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTeamEnvService = "team_env_service"

// TeamEnvService mapped from table <team_env_service>
type TeamEnvService struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	TeamID        string         `gorm:"column:team_id;not null" json:"team_id"`                                 // 团队id
	TeamEnvID     int64          `gorm:"column:team_env_id;not null" json:"team_env_id"`                         // 环境id
	ProtocolType  string         `gorm:"column:protocol_type;not null" json:"protocol_type"`                     // 协议类型
	Name          string         `gorm:"column:name;not null" json:"name"`                                       // 服务名称
	Content       string         `gorm:"column:content;not null" json:"content"`                                 // 服务URL
	CreatedUserID string         `gorm:"column:created_user_id;not null" json:"created_user_id"`                 // 创建人id
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName TeamEnvService's table name
func (*TeamEnvService) TableName() string {
	return TableNameTeamEnvService
}
