// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTeamEnvMysql = "team_env_mysql"

// TeamEnvMysql mapped from table <team_env_mysql>
type TeamEnvMysql struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	TeamID     string         `gorm:"column:team_id;not null" json:"team_id"`                                 // 团队id
	TeamEnvID  int64          `gorm:"column:team_env_id;not null" json:"team_env_id"`                         // 环境变量id
	Type       int32          `gorm:"column:type;not null;default:1" json:"type"`                             // 数据库类型：1-mysql，2-sql server
	ServerName string         `gorm:"column:server_name;not null" json:"server_name"`                         // mysql服务名称
	Host       string         `gorm:"column:host;not null" json:"host"`                                       // 服务地址
	Port       int32          `gorm:"column:port;not null" json:"port"`                                       // 端口号
	User       string         `gorm:"column:user;not null" json:"user"`                                       // 账号
	Password   string         `gorm:"column:password;not null" json:"password"`                               // 密码
	DbName     string         `gorm:"column:db_name;not null" json:"db_name"`                                 // 数据库名称
	Charset    string         `gorm:"column:charset;not null;default:utf8mb4" json:"charset"`                 // 字符编码集
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName TeamEnvMysql's table name
func (*TeamEnvMysql) TableName() string {
	return TableNameTeamEnvMysql
}
