// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTeamEnvService = "team_env_service"

// TeamEnvService mapped from table <team_env_service>
type TeamEnvService struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                // ID
	TeamID        string         `gorm:"column:team_id;not null" json:"team_id"`                           // 团队ID
	TeamEnvID     int64          `gorm:"column:team_env_id;not null" json:"team_env_id"`                   // 环境ID
	Name          string         `gorm:"column:name;not null" json:"name"`                                 // 服务名称
	Content       string         `gorm:"column:content;not null" json:"content"`                           // 服务URL
	Sort          int32          `gorm:"column:sort;not null" json:"sort"`                                 // 排序
	Status        int32          `gorm:"column:status;not null;default:1" json:"status"`                   // 状态：1-正常 2-删除
	CreatedUserID string         `gorm:"column:created_user_id;not null;default:0" json:"created_user_id"` // 创建人ID
	RecentUserID  int64          `gorm:"column:recent_user_id;not null" json:"recent_user_id"`
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName TeamEnvService's table name
func (*TeamEnvService) TableName() string {
	return TableNameTeamEnvService
}
