// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameThirdNoticeGroupRelate = "third_notice_group_relate"

// ThirdNoticeGroupRelate mapped from table <third_notice_group_relate>
type ThirdNoticeGroupRelate struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	GroupID   string         `gorm:"column:group_id;not null" json:"group_id"`          // 通知组id
	NoticeID  string         `gorm:"column:notice_id;not null" json:"notice_id"`        // 通知id
	Params    string         `gorm:"column:params" json:"params"`                       // 通知目标参数
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName ThirdNoticeGroupRelate's table name
func (*ThirdNoticeGroupRelate) TableName() string {
	return TableNameThirdNoticeGroupRelate
}
