// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameThirdNotice = "third_notice"

// ThirdNotice mapped from table <third_notice>
type ThirdNotice struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	NoticeID  string         `gorm:"column:notice_id;not null" json:"notice_id"`        // 通知id
	Name      string         `gorm:"column:name;not null" json:"name"`                  // 通知名称
	ChannelID int64          `gorm:"column:channel_id;not null" json:"channel_id"`      // 三方通知渠道id
	Params    string         `gorm:"column:params" json:"params"`                       // 通知参数
	Status    int32          `gorm:"column:status;not null;default:1" json:"status"`    // 1:启用 2:禁用
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName ThirdNotice's table name
func (*ThirdNotice) TableName() string {
	return TableNameThirdNotice
}
