// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUISceneElement = "ui_scene_element"

// UISceneElement mapped from table <ui_scene_element>
type UISceneElement struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // id
	SceneID    string         `gorm:"column:scene_id;not null" json:"scene_id"`                               // 场景ID
	OperatorID string         `gorm:"column:operator_id;not null" json:"operator_id"`                         // 操作ID
	ElementID  string         `gorm:"column:element_id;not null" json:"element_id"`                           // 元素ID
	TeamID     string         `gorm:"column:team_id;not null" json:"team_id"`                                 // 团队id
	Status     int32          `gorm:"column:status;not null;default:1" json:"status"`                         // 状态 1：正常  2：回收站
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName UISceneElement's table name
func (*UISceneElement) TableName() string {
	return TableNameUISceneElement
}
