// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUISceneOperator = "ui_scene_operator"

// UISceneOperator mapped from table <ui_scene_operator>
type UISceneOperator struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // id
	OperatorID string         `gorm:"column:operator_id;not null" json:"operator_id"`                         // 全局唯一ID
	SceneID    string         `gorm:"column:scene_id;not null" json:"scene_id"`                               // 场景ID
	Name       string         `gorm:"column:name;not null" json:"name"`                                       // 名称
	ParentID   string         `gorm:"column:parent_id;not null;default:0" json:"parent_id"`                   // 父级ID
	Sort       int32          `gorm:"column:sort;not null" json:"sort"`                                       // 排序
	Status     int32          `gorm:"column:status;not null;default:1" json:"status"`                         // 状态：1-正常，2-禁用
	Type       string         `gorm:"column:type;not null" json:"type"`                                       // 步骤类型
	Action     string         `gorm:"column:action;not null" json:"action"`                                   // 步骤方法
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName UISceneOperator's table name
func (*UISceneOperator) TableName() string {
	return TableNameUISceneOperator
}
