// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameVumBuyVersion = "vum_buy_version"

// VumBuyVersion mapped from table <vum_buy_version>
type VumBuyVersion struct {
	ID                int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	VumBuyVersionType int32          `gorm:"column:vum_buy_version_type;not null" json:"vum_buy_version_type"`       // vum套餐类型：1-套餐资源A，2-套餐资源B，3-套餐资源C，4-套餐资源D
	Title             string         `gorm:"column:title;not null" json:"title"`                                     // 购买套餐名称
	VumCount          int64          `gorm:"column:vum_count;not null" json:"vum_count"`                             // VUM额度
	MaxConcurrent     int64          `gorm:"column:max_concurrent;not null" json:"max_concurrent"`                   // 最大并发数
	UnitPrice         float64        `gorm:"column:unit_price;not null" json:"unit_price"`                           // 单价
	Discounts         float64        `gorm:"column:discounts;not null" json:"discounts"`                             // 优惠价格
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 修改时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName VumBuyVersion's table name
func (*VumBuyVersion) TableName() string {
	return TableNameVumBuyVersion
}
