version: "3"
 
services:
 
  redis1:
    image: redis
    volumes:
      - /var/runnergo/redisCluster/7000/:/etc/redis/
      - /var/runnergo/redisCluster/7000/data:/data
    network_mode: host
    command: redis-server /etc/redis/redis.conf
 
  redis2:
    image: redis
    volumes:
      - /var/runnergo/redisCluster/7001/:/etc/redis/
      - /var/runnergo/redisCluster/7001/data:/data
    network_mode: host
    command: redis-server /etc/redis/redis.conf
 
  redis3:
    image: redis
    volumes:
      - /var/runnergo/redisCluster/7002/:/etc/redis/
      - /var/runnergo/redisCluster/7002/data:/data
    network_mode: host
    command: redis-server /etc/redis/redis.conf
  redis4:
    image: redis
    volumes:
      - /var/runnergo/redisCluster/7003/:/etc/redis/
      - /var/runnergo/redisCluster/7003/data:/data
    network_mode: host
    command: redis-server /etc/redis/redis.conf
  redis5:
    image: redis
    volumes:
      - /var/runnergo/redisCluster/7004/:/etc/redis/
      - /var/runnergo/redisCluster/7004/data:/data
    network_mode: host
    command: redis-server /etc/redis/redis.conf
  redis6:
    image: redis
    volumes:
      - /var/runnergo/redisCluster/7005/:/etc/redis/
      - /var/runnergo/redisCluster/7005/data:/data
    network_mode: host
    command: redis-server /etc/redis/redis.conf
 
 
  redis-cluster:
    image: redis
    command: redis-cli -a runnergo!666  --cluster create {节点ip}:7000 {节点ip}:7001 {节点ip}:7002 {节点ip}:7003 {节点ip}:7004 {节点ip}:7005 --cluster-replicas 1  --cluster-yes
    network_mode: "host"
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6