// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                      db,
		AutoPlan:                newAutoPlan(db, opts...),
		AutoPlanEmail:           newAutoPlanEmail(db, opts...),
		AutoPlanReport:          newAutoPlanReport(db, opts...),
		AutoPlanTaskConf:        newAutoPlanTaskConf(db, opts...),
		AutoPlanTimedTaskConf:   newAutoPlanTimedTaskConf(db, opts...),
		Company:                 newCompany(db, opts...),
		Machine:                 newMachine(db, opts...),
		MockTarget:              newMockTarget(db, opts...),
		MockTargetDebugLog:      newMockTargetDebugLog(db, opts...),
		Permission:              newPermission(db, opts...),
		PreinstallConf:          newPreinstallConf(db, opts...),
		PublicFunction:          newPublicFunction(db, opts...),
		ReportMachine:           newReportMachine(db, opts...),
		Role:                    newRole(db, opts...),
		RolePermission:          newRolePermission(db, opts...),
		RoleTypePermission:      newRoleTypePermission(db, opts...),
		Setting:                 newSetting(db, opts...),
		SmsLog:                  newSmsLog(db, opts...),
		StressPlan:              newStressPlan(db, opts...),
		StressPlanEmail:         newStressPlanEmail(db, opts...),
		StressPlanReport:        newStressPlanReport(db, opts...),
		StressPlanTaskConf:      newStressPlanTaskConf(db, opts...),
		StressPlanTimedTaskConf: newStressPlanTimedTaskConf(db, opts...),
		Target:                  newTarget(db, opts...),
		TargetDebugLog:          newTargetDebugLog(db, opts...),
		Team:                    newTeam(db, opts...),
		TeamEnv:                 newTeamEnv(db, opts...),
		TeamEnvDatabase:         newTeamEnvDatabase(db, opts...),
		TeamEnvService:          newTeamEnvService(db, opts...),
		TeamUserQueue:           newTeamUserQueue(db, opts...),
		ThirdNotice:             newThirdNotice(db, opts...),
		ThirdNoticeChannel:      newThirdNoticeChannel(db, opts...),
		ThirdNoticeGroup:        newThirdNoticeGroup(db, opts...),
		ThirdNoticeGroupEvent:   newThirdNoticeGroupEvent(db, opts...),
		ThirdNoticeGroupRelate:  newThirdNoticeGroupRelate(db, opts...),
		User:                    newUser(db, opts...),
		UserCollectInfo:         newUserCollectInfo(db, opts...),
		UserCompany:             newUserCompany(db, opts...),
		UserRole:                newUserRole(db, opts...),
		UserTeam:                newUserTeam(db, opts...),
		UserTeamCollection:      newUserTeamCollection(db, opts...),
		Variable:                newVariable(db, opts...),
		VariableImport:          newVariableImport(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AutoPlan                autoPlan
	AutoPlanEmail           autoPlanEmail
	AutoPlanReport          autoPlanReport
	AutoPlanTaskConf        autoPlanTaskConf
	AutoPlanTimedTaskConf   autoPlanTimedTaskConf
	Company                 company
	Machine                 machine
	MockTarget              mockTarget
	MockTargetDebugLog      mockTargetDebugLog
	Permission              permission
	PreinstallConf          preinstallConf
	PublicFunction          publicFunction
	ReportMachine           reportMachine
	Role                    role
	RolePermission          rolePermission
	RoleTypePermission      roleTypePermission
	Setting                 setting
	SmsLog                  smsLog
	StressPlan              stressPlan
	StressPlanEmail         stressPlanEmail
	StressPlanReport        stressPlanReport
	StressPlanTaskConf      stressPlanTaskConf
	StressPlanTimedTaskConf stressPlanTimedTaskConf
	Target                  target
	TargetDebugLog          targetDebugLog
	Team                    team
	TeamEnv                 teamEnv
	TeamEnvDatabase         teamEnvDatabase
	TeamEnvService          teamEnvService
	TeamUserQueue           teamUserQueue
	ThirdNotice             thirdNotice
	ThirdNoticeChannel      thirdNoticeChannel
	ThirdNoticeGroup        thirdNoticeGroup
	ThirdNoticeGroupEvent   thirdNoticeGroupEvent
	ThirdNoticeGroupRelate  thirdNoticeGroupRelate
	User                    user
	UserCollectInfo         userCollectInfo
	UserCompany             userCompany
	UserRole                userRole
	UserTeam                userTeam
	UserTeamCollection      userTeamCollection
	Variable                variable
	VariableImport          variableImport
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		AutoPlan:                q.AutoPlan.clone(db),
		AutoPlanEmail:           q.AutoPlanEmail.clone(db),
		AutoPlanReport:          q.AutoPlanReport.clone(db),
		AutoPlanTaskConf:        q.AutoPlanTaskConf.clone(db),
		AutoPlanTimedTaskConf:   q.AutoPlanTimedTaskConf.clone(db),
		Company:                 q.Company.clone(db),
		Machine:                 q.Machine.clone(db),
		MockTarget:              q.MockTarget.clone(db),
		MockTargetDebugLog:      q.MockTargetDebugLog.clone(db),
		Permission:              q.Permission.clone(db),
		PreinstallConf:          q.PreinstallConf.clone(db),
		PublicFunction:          q.PublicFunction.clone(db),
		ReportMachine:           q.ReportMachine.clone(db),
		Role:                    q.Role.clone(db),
		RolePermission:          q.RolePermission.clone(db),
		RoleTypePermission:      q.RoleTypePermission.clone(db),
		Setting:                 q.Setting.clone(db),
		SmsLog:                  q.SmsLog.clone(db),
		StressPlan:              q.StressPlan.clone(db),
		StressPlanEmail:         q.StressPlanEmail.clone(db),
		StressPlanReport:        q.StressPlanReport.clone(db),
		StressPlanTaskConf:      q.StressPlanTaskConf.clone(db),
		StressPlanTimedTaskConf: q.StressPlanTimedTaskConf.clone(db),
		Target:                  q.Target.clone(db),
		TargetDebugLog:          q.TargetDebugLog.clone(db),
		Team:                    q.Team.clone(db),
		TeamEnv:                 q.TeamEnv.clone(db),
		TeamEnvDatabase:         q.TeamEnvDatabase.clone(db),
		TeamEnvService:          q.TeamEnvService.clone(db),
		TeamUserQueue:           q.TeamUserQueue.clone(db),
		ThirdNotice:             q.ThirdNotice.clone(db),
		ThirdNoticeChannel:      q.ThirdNoticeChannel.clone(db),
		ThirdNoticeGroup:        q.ThirdNoticeGroup.clone(db),
		ThirdNoticeGroupEvent:   q.ThirdNoticeGroupEvent.clone(db),
		ThirdNoticeGroupRelate:  q.ThirdNoticeGroupRelate.clone(db),
		User:                    q.User.clone(db),
		UserCollectInfo:         q.UserCollectInfo.clone(db),
		UserCompany:             q.UserCompany.clone(db),
		UserRole:                q.UserRole.clone(db),
		UserTeam:                q.UserTeam.clone(db),
		UserTeamCollection:      q.UserTeamCollection.clone(db),
		Variable:                q.Variable.clone(db),
		VariableImport:          q.VariableImport.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		AutoPlan:                q.AutoPlan.replaceDB(db),
		AutoPlanEmail:           q.AutoPlanEmail.replaceDB(db),
		AutoPlanReport:          q.AutoPlanReport.replaceDB(db),
		AutoPlanTaskConf:        q.AutoPlanTaskConf.replaceDB(db),
		AutoPlanTimedTaskConf:   q.AutoPlanTimedTaskConf.replaceDB(db),
		Company:                 q.Company.replaceDB(db),
		Machine:                 q.Machine.replaceDB(db),
		MockTarget:              q.MockTarget.replaceDB(db),
		MockTargetDebugLog:      q.MockTargetDebugLog.replaceDB(db),
		Permission:              q.Permission.replaceDB(db),
		PreinstallConf:          q.PreinstallConf.replaceDB(db),
		PublicFunction:          q.PublicFunction.replaceDB(db),
		ReportMachine:           q.ReportMachine.replaceDB(db),
		Role:                    q.Role.replaceDB(db),
		RolePermission:          q.RolePermission.replaceDB(db),
		RoleTypePermission:      q.RoleTypePermission.replaceDB(db),
		Setting:                 q.Setting.replaceDB(db),
		SmsLog:                  q.SmsLog.replaceDB(db),
		StressPlan:              q.StressPlan.replaceDB(db),
		StressPlanEmail:         q.StressPlanEmail.replaceDB(db),
		StressPlanReport:        q.StressPlanReport.replaceDB(db),
		StressPlanTaskConf:      q.StressPlanTaskConf.replaceDB(db),
		StressPlanTimedTaskConf: q.StressPlanTimedTaskConf.replaceDB(db),
		Target:                  q.Target.replaceDB(db),
		TargetDebugLog:          q.TargetDebugLog.replaceDB(db),
		Team:                    q.Team.replaceDB(db),
		TeamEnv:                 q.TeamEnv.replaceDB(db),
		TeamEnvDatabase:         q.TeamEnvDatabase.replaceDB(db),
		TeamEnvService:          q.TeamEnvService.replaceDB(db),
		TeamUserQueue:           q.TeamUserQueue.replaceDB(db),
		ThirdNotice:             q.ThirdNotice.replaceDB(db),
		ThirdNoticeChannel:      q.ThirdNoticeChannel.replaceDB(db),
		ThirdNoticeGroup:        q.ThirdNoticeGroup.replaceDB(db),
		ThirdNoticeGroupEvent:   q.ThirdNoticeGroupEvent.replaceDB(db),
		ThirdNoticeGroupRelate:  q.ThirdNoticeGroupRelate.replaceDB(db),
		User:                    q.User.replaceDB(db),
		UserCollectInfo:         q.UserCollectInfo.replaceDB(db),
		UserCompany:             q.UserCompany.replaceDB(db),
		UserRole:                q.UserRole.replaceDB(db),
		UserTeam:                q.UserTeam.replaceDB(db),
		UserTeamCollection:      q.UserTeamCollection.replaceDB(db),
		Variable:                q.Variable.replaceDB(db),
		VariableImport:          q.VariableImport.replaceDB(db),
	}
}

type queryCtx struct {
	AutoPlan                *autoPlanDo
	AutoPlanEmail           *autoPlanEmailDo
	AutoPlanReport          *autoPlanReportDo
	AutoPlanTaskConf        *autoPlanTaskConfDo
	AutoPlanTimedTaskConf   *autoPlanTimedTaskConfDo
	Company                 *companyDo
	Machine                 *machineDo
	MockTarget              *mockTargetDo
	MockTargetDebugLog      *mockTargetDebugLogDo
	Permission              *permissionDo
	PreinstallConf          *preinstallConfDo
	PublicFunction          *publicFunctionDo
	ReportMachine           *reportMachineDo
	Role                    *roleDo
	RolePermission          *rolePermissionDo
	RoleTypePermission      *roleTypePermissionDo
	Setting                 *settingDo
	SmsLog                  *smsLogDo
	StressPlan              *stressPlanDo
	StressPlanEmail         *stressPlanEmailDo
	StressPlanReport        *stressPlanReportDo
	StressPlanTaskConf      *stressPlanTaskConfDo
	StressPlanTimedTaskConf *stressPlanTimedTaskConfDo
	Target                  *targetDo
	TargetDebugLog          *targetDebugLogDo
	Team                    *teamDo
	TeamEnv                 *teamEnvDo
	TeamEnvDatabase         *teamEnvDatabaseDo
	TeamEnvService          *teamEnvServiceDo
	TeamUserQueue           *teamUserQueueDo
	ThirdNotice             *thirdNoticeDo
	ThirdNoticeChannel      *thirdNoticeChannelDo
	ThirdNoticeGroup        *thirdNoticeGroupDo
	ThirdNoticeGroupEvent   *thirdNoticeGroupEventDo
	ThirdNoticeGroupRelate  *thirdNoticeGroupRelateDo
	User                    *userDo
	UserCollectInfo         *userCollectInfoDo
	UserCompany             *userCompanyDo
	UserRole                *userRoleDo
	UserTeam                *userTeamDo
	UserTeamCollection      *userTeamCollectionDo
	Variable                *variableDo
	VariableImport          *variableImportDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AutoPlan:                q.AutoPlan.WithContext(ctx),
		AutoPlanEmail:           q.AutoPlanEmail.WithContext(ctx),
		AutoPlanReport:          q.AutoPlanReport.WithContext(ctx),
		AutoPlanTaskConf:        q.AutoPlanTaskConf.WithContext(ctx),
		AutoPlanTimedTaskConf:   q.AutoPlanTimedTaskConf.WithContext(ctx),
		Company:                 q.Company.WithContext(ctx),
		Machine:                 q.Machine.WithContext(ctx),
		MockTarget:              q.MockTarget.WithContext(ctx),
		MockTargetDebugLog:      q.MockTargetDebugLog.WithContext(ctx),
		Permission:              q.Permission.WithContext(ctx),
		PreinstallConf:          q.PreinstallConf.WithContext(ctx),
		PublicFunction:          q.PublicFunction.WithContext(ctx),
		ReportMachine:           q.ReportMachine.WithContext(ctx),
		Role:                    q.Role.WithContext(ctx),
		RolePermission:          q.RolePermission.WithContext(ctx),
		RoleTypePermission:      q.RoleTypePermission.WithContext(ctx),
		Setting:                 q.Setting.WithContext(ctx),
		SmsLog:                  q.SmsLog.WithContext(ctx),
		StressPlan:              q.StressPlan.WithContext(ctx),
		StressPlanEmail:         q.StressPlanEmail.WithContext(ctx),
		StressPlanReport:        q.StressPlanReport.WithContext(ctx),
		StressPlanTaskConf:      q.StressPlanTaskConf.WithContext(ctx),
		StressPlanTimedTaskConf: q.StressPlanTimedTaskConf.WithContext(ctx),
		Target:                  q.Target.WithContext(ctx),
		TargetDebugLog:          q.TargetDebugLog.WithContext(ctx),
		Team:                    q.Team.WithContext(ctx),
		TeamEnv:                 q.TeamEnv.WithContext(ctx),
		TeamEnvDatabase:         q.TeamEnvDatabase.WithContext(ctx),
		TeamEnvService:          q.TeamEnvService.WithContext(ctx),
		TeamUserQueue:           q.TeamUserQueue.WithContext(ctx),
		ThirdNotice:             q.ThirdNotice.WithContext(ctx),
		ThirdNoticeChannel:      q.ThirdNoticeChannel.WithContext(ctx),
		ThirdNoticeGroup:        q.ThirdNoticeGroup.WithContext(ctx),
		ThirdNoticeGroupEvent:   q.ThirdNoticeGroupEvent.WithContext(ctx),
		ThirdNoticeGroupRelate:  q.ThirdNoticeGroupRelate.WithContext(ctx),
		User:                    q.User.WithContext(ctx),
		UserCollectInfo:         q.UserCollectInfo.WithContext(ctx),
		UserCompany:             q.UserCompany.WithContext(ctx),
		UserRole:                q.UserRole.WithContext(ctx),
		UserTeam:                q.UserTeam.WithContext(ctx),
		UserTeamCollection:      q.UserTeamCollection.WithContext(ctx),
		Variable:                q.Variable.WithContext(ctx),
		VariableImport:          q.VariableImport.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
