// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Runner-Go-Team/RunnerGo-management-open/internal/pkg/dal/model"
)

func newUIPlanTaskConf(db *gorm.DB, opts ...gen.DOOption) uIPlanTaskConf {
	_uIPlanTaskConf := uIPlanTaskConf{}

	_uIPlanTaskConf.uIPlanTaskConfDo.UseDB(db, opts...)
	_uIPlanTaskConf.uIPlanTaskConfDo.UseModel(&model.UIPlanTaskConf{})

	tableName := _uIPlanTaskConf.uIPlanTaskConfDo.TableName()
	_uIPlanTaskConf.ALL = field.NewAsterisk(tableName)
	_uIPlanTaskConf.ID = field.NewInt32(tableName, "id")
	_uIPlanTaskConf.PlanID = field.NewString(tableName, "plan_id")
	_uIPlanTaskConf.TeamID = field.NewString(tableName, "team_id")
	_uIPlanTaskConf.TaskType = field.NewInt32(tableName, "task_type")
	_uIPlanTaskConf.SceneRunOrder = field.NewInt32(tableName, "scene_run_order")
	_uIPlanTaskConf.RunUserID = field.NewString(tableName, "run_user_id")
	_uIPlanTaskConf.CreatedAt = field.NewTime(tableName, "created_at")
	_uIPlanTaskConf.UpdatedAt = field.NewTime(tableName, "updated_at")
	_uIPlanTaskConf.DeletedAt = field.NewField(tableName, "deleted_at")

	_uIPlanTaskConf.fillFieldMap()

	return _uIPlanTaskConf
}

type uIPlanTaskConf struct {
	uIPlanTaskConfDo uIPlanTaskConfDo

	ALL           field.Asterisk
	ID            field.Int32  // 配置ID
	PlanID        field.String // 计划ID
	TeamID        field.String // 团队ID
	TaskType      field.Int32  // 任务类型：1-普通模式，2-定时任务
	SceneRunOrder field.Int32  // 场景运行次序：1-顺序执行，2-同时执行
	RunUserID     field.String // 运行人用户ID
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (u uIPlanTaskConf) Table(newTableName string) *uIPlanTaskConf {
	u.uIPlanTaskConfDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u uIPlanTaskConf) As(alias string) *uIPlanTaskConf {
	u.uIPlanTaskConfDo.DO = *(u.uIPlanTaskConfDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *uIPlanTaskConf) updateTableName(table string) *uIPlanTaskConf {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.PlanID = field.NewString(table, "plan_id")
	u.TeamID = field.NewString(table, "team_id")
	u.TaskType = field.NewInt32(table, "task_type")
	u.SceneRunOrder = field.NewInt32(table, "scene_run_order")
	u.RunUserID = field.NewString(table, "run_user_id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *uIPlanTaskConf) WithContext(ctx context.Context) *uIPlanTaskConfDo {
	return u.uIPlanTaskConfDo.WithContext(ctx)
}

func (u uIPlanTaskConf) TableName() string { return u.uIPlanTaskConfDo.TableName() }

func (u uIPlanTaskConf) Alias() string { return u.uIPlanTaskConfDo.Alias() }

func (u *uIPlanTaskConf) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *uIPlanTaskConf) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 9)
	u.fieldMap["id"] = u.ID
	u.fieldMap["plan_id"] = u.PlanID
	u.fieldMap["team_id"] = u.TeamID
	u.fieldMap["task_type"] = u.TaskType
	u.fieldMap["scene_run_order"] = u.SceneRunOrder
	u.fieldMap["run_user_id"] = u.RunUserID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u uIPlanTaskConf) clone(db *gorm.DB) uIPlanTaskConf {
	u.uIPlanTaskConfDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u uIPlanTaskConf) replaceDB(db *gorm.DB) uIPlanTaskConf {
	u.uIPlanTaskConfDo.ReplaceDB(db)
	return u
}

type uIPlanTaskConfDo struct{ gen.DO }

func (u uIPlanTaskConfDo) Debug() *uIPlanTaskConfDo {
	return u.withDO(u.DO.Debug())
}

func (u uIPlanTaskConfDo) WithContext(ctx context.Context) *uIPlanTaskConfDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u uIPlanTaskConfDo) ReadDB() *uIPlanTaskConfDo {
	return u.Clauses(dbresolver.Read)
}

func (u uIPlanTaskConfDo) WriteDB() *uIPlanTaskConfDo {
	return u.Clauses(dbresolver.Write)
}

func (u uIPlanTaskConfDo) Session(config *gorm.Session) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Session(config))
}

func (u uIPlanTaskConfDo) Clauses(conds ...clause.Expression) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u uIPlanTaskConfDo) Returning(value interface{}, columns ...string) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u uIPlanTaskConfDo) Not(conds ...gen.Condition) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u uIPlanTaskConfDo) Or(conds ...gen.Condition) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u uIPlanTaskConfDo) Select(conds ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u uIPlanTaskConfDo) Where(conds ...gen.Condition) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u uIPlanTaskConfDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *uIPlanTaskConfDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u uIPlanTaskConfDo) Order(conds ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u uIPlanTaskConfDo) Distinct(cols ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u uIPlanTaskConfDo) Omit(cols ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u uIPlanTaskConfDo) Join(table schema.Tabler, on ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u uIPlanTaskConfDo) LeftJoin(table schema.Tabler, on ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u uIPlanTaskConfDo) RightJoin(table schema.Tabler, on ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u uIPlanTaskConfDo) Group(cols ...field.Expr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u uIPlanTaskConfDo) Having(conds ...gen.Condition) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u uIPlanTaskConfDo) Limit(limit int) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u uIPlanTaskConfDo) Offset(offset int) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u uIPlanTaskConfDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u uIPlanTaskConfDo) Unscoped() *uIPlanTaskConfDo {
	return u.withDO(u.DO.Unscoped())
}

func (u uIPlanTaskConfDo) Create(values ...*model.UIPlanTaskConf) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u uIPlanTaskConfDo) CreateInBatches(values []*model.UIPlanTaskConf, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u uIPlanTaskConfDo) Save(values ...*model.UIPlanTaskConf) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u uIPlanTaskConfDo) First() (*model.UIPlanTaskConf, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UIPlanTaskConf), nil
	}
}

func (u uIPlanTaskConfDo) Take() (*model.UIPlanTaskConf, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UIPlanTaskConf), nil
	}
}

func (u uIPlanTaskConfDo) Last() (*model.UIPlanTaskConf, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UIPlanTaskConf), nil
	}
}

func (u uIPlanTaskConfDo) Find() ([]*model.UIPlanTaskConf, error) {
	result, err := u.DO.Find()
	return result.([]*model.UIPlanTaskConf), err
}

func (u uIPlanTaskConfDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UIPlanTaskConf, err error) {
	buf := make([]*model.UIPlanTaskConf, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u uIPlanTaskConfDo) FindInBatches(result *[]*model.UIPlanTaskConf, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u uIPlanTaskConfDo) Attrs(attrs ...field.AssignExpr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u uIPlanTaskConfDo) Assign(attrs ...field.AssignExpr) *uIPlanTaskConfDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u uIPlanTaskConfDo) Joins(fields ...field.RelationField) *uIPlanTaskConfDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u uIPlanTaskConfDo) Preload(fields ...field.RelationField) *uIPlanTaskConfDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u uIPlanTaskConfDo) FirstOrInit() (*model.UIPlanTaskConf, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UIPlanTaskConf), nil
	}
}

func (u uIPlanTaskConfDo) FirstOrCreate() (*model.UIPlanTaskConf, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UIPlanTaskConf), nil
	}
}

func (u uIPlanTaskConfDo) FindByPage(offset int, limit int) (result []*model.UIPlanTaskConf, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u uIPlanTaskConfDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u uIPlanTaskConfDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u uIPlanTaskConfDo) Delete(models ...*model.UIPlanTaskConf) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *uIPlanTaskConfDo) withDO(do gen.Dao) *uIPlanTaskConfDo {
	u.DO = *do.(*gen.DO)
	return u
}
