package consts

const (
	CollectFolder                   = "folder"
	CollectAPI                      = "api"
	CollectScene                    = "scene"
	CollectTask                     = "task"
	CollectFlow                     = "flow"
	CollectReportTask               = "report_task"
	CollectChangeReportConf         = "change_report_conf"
	CollectMachineMonitorData       = "machine_monitor_data"
	CollectOperationLog             = "operation_log"
	CollectSqlDetail                = "sql_detail"
	CollectTcpDetail                = "tcp_detail"
	CollectWebsocketDetail          = "websocket_detail"
	CollectMqttDetail               = "mqtt_detail"
	CollectDubboDetail              = "dubbo_detail"
	CollectAPIDebug                 = "api_debug"
	CollectSceneDebug               = "scene_debug"
	CollectSceneCaseFlow            = "scene_case_flow"
	CollectStressDebug              = "stress_debug"
	CollectDebugStatus              = "debug_status"
	CollectReportData               = "report_data"
	CollectAutoReport               = "auto_report"
	CollectAutoReportDetailData     = "auto_report_detail_data"
	CollectGlobalParam              = "global_param"
	CollectSceneParam               = "scene_param"
	CollectSQLDebug                 = "sql_debug"
	CollectTcpDebug                 = "tcp_debug"
	CollectMock                     = "mock"
	CollectWebsocketDebug           = "ws_debug"
	CollectDubboDebug               = "dubbo_debug"
	CollectMqttDebug                = "mqtt_debug"
	CollectTargetHistoryRecord      = "target_history_record"
	CollectTargetTagVersion         = "target_tag_version"
	CollectTargetDebugLog           = "target_debug_log"
	CollectTargetCiteRelation       = "target_cite_relation" // 测试对象引用关系表
	CollectSceneCiteRelation        = "scene_cite_relation"  // 场景引用关系表
	CollectUISceneOperator          = "ui_scene_operator"
	CollectUISendSceneOperator      = "ui_send_scene_operator"
	CollectUISendSceneOperatorDebug = "ui_send_scene_operator_debug"
	CollectUISendReport             = "ui_send_report"

	StressDebugLogAll         = "all"
	StressDebugLogOnlyError   = "only_error"
	StressDebugLogOnlySuccess = "only_success"
	StressDebugLogStopDebug   = "stop"
)
