package consts

const (
	CollectFolder             = "folder"
	CollectAPI                = "api"
	CollectScene              = "scene"
	CollectTask               = "task"
	CollectFlow               = "flow"
	CollectReportTask         = "report_task"
	CollectChangeReportConf   = "change_report_conf"
	CollectMachineMonitorData = "machine_monitor_data"
	CollectOperationLog       = "operation_log"
	CollectSqlDetail          = "sql_detail"
	CollectTcpDetail          = "tcp_detail"
	CollectWebsocketDetail    = "websocket_detail"
	CollectMqttDetail         = "mqtt_detail"
	CollectDubboDetail        = "dubbo_detail"

	CollectAPIDebug             = "api_debug"
	CollectSceneDebug           = "scene_debug"
	CollectSceneCaseFlow        = "scene_case_flow"
	CollectStressDebug          = "stress_debug"
	CollectDebugStatus          = "debug_status"
	CollectReportData           = "report_data"
	CollectAutoReport           = "auto_report"
	CollectAutoReportDetailData = "auto_report_detail_data"
	CollectGlobalParam          = "global_param"
	CollectSceneParam           = "scene_param"
	CollectSQLDebug             = "sql_debug"
	CollectTcpDebug             = "tcp_debug"
	CollectMock                 = "mock"
	CollectWebsocketDebug       = "ws_debug"
	CollectDubboDebug           = "dubbo_debug"
	CollectMqttDebug            = "mqtt_debug"

	All         = "all"
	OnlyError   = "only_error"
	OnlySuccess = "only_success"
	StopDebug   = "stop"
)
